name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    #####Running docker container in a job##########
    container:
      image: node:10.18.0-jessie
    steps:
      - uses: actions/checkout@v1
    ######Running local script using docker ###############
      - name: Run a local script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: "Hello World"
    #####Running Docker container in a step###############
      - name: log node version
        run: node -v 
      - name: step with docker 
    #####Using docker image in a step######################
        uses: docker://node:12.14.1-alpine3.10
    #####Overriding dockerfile entrypoint###################
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World!!'
      - name: log node version again
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/usr/local/bin/node'
          args: '-v'
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10

    steps:
      - name:  Log node version
        run: |
          node -v
          cat /etc/os-release
