name: Context_testing
on: [ push, pull_request ]

jobs:
  githubFunctions:
    runs-on: ubuntu-18.04
    steps:
      - name: github functions output
        run: |
          echo ${{contains('hello', 'll')}}
          echo ${{ startsWith('hello', 'hi')  }}
          echo ${{ endsWith('hello', 'lo')}}
          echo ${{ format('hello {0} {1} {2}', 'World', '!', '!') }}


  dump_contexts_to_log:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'     ############## Conditional statement with if the event type is push
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: eccho '${{ toJSON(github) }}'
      - name: Dump job context
        if: failure()                   ############## This step will execute even if previous step is failed
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        if: always()                   ############### This step will always execute irrespective of previous step status
        run: echo '${{ toJSON(matrix) }}'