name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    needs: ["run-python-version"]
    steps:
      - name: echo a string
        run: echo "Hello Worlds."
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-python-version:
    runs-on: ubuntu-18.04
    steps:
      - name: Python version commands
        run: python -V




